import type { Metadata } from "next";
import { Inter, Archivo } from "next/font/google";
import "./globals.css";
import { AuthorizationWrapper } from "./util/authContext";

// Load Google Fonts
const inter = Inter({ subsets: ["latin"] });
const archivo = Archivo({ weight: ["400", "700"], subsets: ["latin"] });

// Metadata for the layout
export const metadata: Metadata = {
  title: "WordScape | Internal",
  description: "Generated by create next app",
};

// Define the layout component
export default function RootLayout({
  children,
  types,
}: {
  children: React.ReactNode;
  types?: any;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} font-archivo`}>{children}</body>
    </html>
  );
}
