import type { Metadata } from "next";
import { Inter, Archivo } from "next/font/google";
import "./globals.css";
import { AuthorizationWrapper } from "./util/authContext";

const inter = Inter({ subsets: ["latin"] });
const archivo = Archivo({ weight: ["400", "700"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "WordScape | Internal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} font-archivo`}>
        {/* Wrap children with AuthorizationWrapper */}
        {children}
      </body>
    </html>
  );
}
