import type { Metadata } from "next";
import { Inter, Archivo } from "next/font/google";
import "./globals.css";
import ClientLayout from "./ClientLayout";

// Load Google Fonts
const inter = Inter({ subsets: ["latin"] });
const archivo = Archivo({ weight: ["400", "700"], subsets: ["latin"] });

// Metadata for the layout
export const metadata: Metadata = {
  title: "WordScape | Internal",
  description: "Generated by create next app",
};

// Define the layout component
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} font-archivo`}>
        <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  );
}
